name: Run Tests on Push to Master

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Echo test
        run: echo "Running tests on master branch"
