name: Run Tests on Push to Master

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Echo test
        run: echo "Running tests on main branch"
